### ISSUE TITLE
Getting a warning popup when clicking on Okta login

### ISSUE THREAD

**Issue by aamirrideo** [oktadeveloper/okta-appauth-xamarin-example#1]
Hi,

I am getting a confirmation message when trying to click on the login button in okta.
Is there a way to suppress it.
![okta error](https://user-images.githubusercontent.com/39773712/40734017-378c2226-6405-11e8-8ab9-c5acca21669b.PNG)

**Comment by nbarbettini** [comment]
This is a system dialog that was added in iOS 11. More info here: https://github.com/openid/AppAuth-iOS/issues/177
